# Docs/Config: https://stylelint.io/user-guide/configure

ignoreFiles:
  - node_modules/**

extends:
  - stylelint-config-standard

# Docs/Rules: https://stylelint.io/user-guide/rules/list
rules:
  indentation: 2
  linebreaks: unix
  max-empty-lines: 1
  number-leading-zero: null
  declaration-block-trailing-semicolon: always
  block-closing-brace-newline-after: always
  color-hex-length: long
  no-eol-whitespace: [true, {ignore: empty-lines}]
  at-rule-no-unknown: [true, {ignoreAtRules: define-mixin}]
  property-no-unknown: [true, {ignoreProperties: font-smooth}]
